# Generated by Django 5.2.8 on 2025-11-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='resultado',
            field=models.CharField(choices=[('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], max_length=10),
        ),
    ]
